services:
  bank-db:
    container_name: bank-db
    image: postgres:latest
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres/bank
    networks:
      - bank
    ports:
      - "5432:5432"
  bank-backend:
    container_name: bank-backend
    image: bank-backend-img
    environment:
      spring.profiles.active: dev
    depends_on:
      - bank-db
    ports:
      - "8080:8080"
    networks:
      - bank

networks:
  bank:
    driver: bridge